### ISSUE TITLE
Teleporter SFX is too quiet upon arrival at background teleporters.

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#10]
Teleporting to background teleporters (from either a foreground teleporter or from another background teleporter gives a quieter than normal 'ZAP' SFX upon arrival. (Only the 2nd ZAP SFX is affected. The departure 'ZAP' is correct).

[teleporter SFX bug.zip](https://github.com/AliveTeam/alive_reversing/files/2706122/teleporter.SFX.bug.zip)

**Comment by paulsapps** [comment]
Closed wrong issue, not fixed yet :(

**Comment by mlgthatsme** [comment]
Issue fixed with 26214c5
