### ISSUE TITLE
AO Rev Bug - Controls menu rebinds wrong actions

### ISSUE THREAD

**Issue by rozniak** [AliveTeam/alive_reversing#1010]
Found in build: 54f7418412105462e363123380ed9719ee4ae344
Last working build number: N/A

Description of issue:
Rebinding controls using the in game menu rebinds the wrong things:
- Run rebinds right
- Sneak rebinds down
- Jump rebinds nothing
- Action/Throw are the wrong way around
- Crouch rebinds sneak

Editing `abe2.ini` manually works, it's the in game menu that is broken.

Here's my usual control scheme:
```
run = Q
sneak = A
jump = W
action = S
throw = O
fart = E
```

Here's what I ended up with when I tried this binding in game:
```
run = W
sneak = E
jump =
action = O
throw = S
fart =
```

Steps to repro:
Rebind controls using the in game menu - notice that menu navigation using right and down keys use rebound keys and in game controls are very mixed up.

**Comment by paulsapps** [comment]
@pryon likes fixing these sorts of bugs 😏

**Comment by pryon** [comment]
Yeah the menus in AO are kinda borked, a big menu overhaul is planned 😉

**Comment by pryon** [comment]
@paulsapps this can be closed now
