### ISSUE TITLE
AO Rev Bug - Game does not register completion of Paramonia or Scrabania

### ISSUE THREAD

**Issue by rozniak** [AliveTeam/alive_reversing#1011]
Found in build: 54f7418412105462e363123380ed9719ee4ae344
Last working build number: N/A

Description of issue:
In my playthrough of AO, the game does not register either Paramonia or Scrabania as completed upon return from the temple trials. I completed both, returned to Monsaic Lines without Shrykull powers and was still able to access either level after activating the wells as if they were incomplete.

Steps to repro:
Normal playthrough of the game - after returning to Monsaic Lines from either temple trial you should be able to go back in the well again as if you didn't complete either.

**Comment by paulsapps** [comment]
could be OG according to @mouzedrift I think the abe object is setting the flags so could add some debug logging specifically for this if it always repros.
