### ISSUE TITLE
AO OG Bug - Gamespeak keys held for a short time don't trigger gamespeak 

### ISSUE THREAD

**Issue by pryon** [AliveTeam/alive_reversing#1037]
**Description of issue:** 
If any of the gamespeak keys is pressed very shortly, Abe will get "nudged" a few pixels to the side and then back, but won't actually talk.
The gamespeak key has to be held for at least 500ms to get Abe to talk.

**Steps to repro:** 
1. Start a new game
2. Hit the <kbd>1</kbd> key on the keyboard very quickly
3. Notice how Abe is nudged but does not talk
4. Now hold the same key for a little longer
5. He talks now!

**Comment by paulsapps** [comment]
@pryon is this fixed? 🤔

**Comment by mouzedrift** [comment]
fixed
