### ISSUE TITLE
AO Standalone Rev Bug - Speedrun strat that is supposed to blow up mines by touching them doesn't work

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#1089]
Standalone (broken):
https://user-images.githubusercontent.com/43358824/106389792-9f86bc00-63e5-11eb-8d82-243ccdad35cb.mp4

DLL (works as intended):
https://user-images.githubusercontent.com/43358824/106389816-add4d800-63e5-11eb-957b-a7fa74be1adf.mp4

**Comment by paulsapps** [comment]
Issue tracked to Math_SquareRoot_FP_451210 - prob need to check AE_IMPL's on bugs that only repro in standalone for future ref.
