### ISSUE TITLE
flying mines are teleporting and faster 

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#11]
self explanatory 
[teleporting mines.zip](https://github.com/AliveTeam/alive_reversing/files/2706125/teleporting.mines.zip)

**Comment by UltraStars3000** [comment]
This makes the game crashes here after being in the secret for few moments
[Block 2 mines crash.zip](https://github.com/AliveTeam/alive_reversing/files/2717421/Block.2.mines.crash.zip)

**Comment by mouzee1337** [comment]
> 
> 
> This makes the game crashes here after being in the secret for few moments
> [Block 2 mines crash.zip](https://github.com/AliveTeam/alive_reversing/files/2717421/Block.2.mines.crash.zip)
not for me tho... 🤔 
(atleast not the old version :4Head:)

**Comment by paulsapps** [comment]
Issue tracked to function `PathLine::MoveOnLine_418260` nothing else known yet.

**Comment by mouzee1337** [comment]
fixed 🥇

**Comment by paulsapps** [comment]
💯
