### ISSUE TITLE
AE Rev Bug - The game segfaults on exit

### ISSUE THREAD

**Issue by Nemin32** [AliveTeam/alive_reversing#1131]
Found in build: 23b28764cc6d6177bb318f60d341e0b2108ed23d

Description of issue:
When you exit the game, the screen goes white for a second, then segfaults. This happens on Linux, I'm not sure about other platforms.

Steps to repro:
1. Launch game in terminal.
2. Exit.
3. Observe terminal output and `Segmentation fault (core dumped)`.

**Comment by paulsapps** [comment]
I think this fixes the one see, but the asan issue still exists
