### ISSUE TITLE
AE Rev Bug - Mine car gets stuck in a certain situation

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#1141]
![image](https://user-images.githubusercontent.com/43358824/110706456-29515280-81f8-11eb-87ff-f78f62d49490.png)
save:
[!.zip](https://github.com/AliveTeam/alive_reversing/files/6119214/default.zip)

function: ``MineCar::State_1_ParkedWithAbe()``

**Comment by rozniak** [comment]
I am working on a fix for this - I have the minecar no longer stuck on the first vertical wall, but it gets stuck on the second now (downwards).

**Comment by rozniak** [comment]
Seem to have fixed that now, just need to make sure I haven't caused a regression somewhere else.
