### ISSUE TITLE
AO OG Bug - screen flicker from last frame & missing music/video

### ISSUE THREAD

**Issue by coreybruce** [AliveTeam/alive_reversing#1162]
**Description of issue:** 
Just want to report a bug where the screen will flicker with either the last frame at times or something random for a split second also the videos and music are missing.

**Steps to repro:** 
Play game

If you need more information please let me know.

**Comment by paulsapps** [comment]
This seems to only happen on Linux

**Comment by coreybruce** [comment]
I'll have to test to see if it does it on my PC and just a bug on the Raspberry pi or Linux itself.

Wanted to also ask off topic if there will be enhancements added to this open source version of the game like 16:9 or up-scaling and anti aliasing?

**Comment by paulsapps** [comment]
yeah there will be - if you have discord you can join the server to see progress on such topics :)

**Comment by coreybruce** [comment]
> yeah there will be - if you have discord you can join the server to see progress on such topics :)

yeah, shoot me a link and I will join :D :+1:

**Comment by paulsapps** [comment]
yeah it should be in the readme.md - https://discord.gg/khs6KKS

**Comment by paulsapps** [comment]
apparently this bug can be worked around by forcing SDL2 to use the software instead of the opengl backend

**Comment by coreybruce** [comment]
Oh ok so will it be switched to SDL since it probs doesn't need OpenGL or will there be some sort of launch argument for SDL?

**Comment by paulsapps** [comment]
SDL uses software, opengl and other "backends" but this bug only manifests with openg, the issue is in our code not SDL

**Comment by coreybruce** [comment]
I assume this is already being worked on? :)

**Comment by paulsapps** [comment]
breaking commit https://github.com/AliveTeam/alive_reversing/commit/e15a5b3237e5bf1fd234250fb8e49506e6dea119#diff-10cb582f11be60e1f4e8c34f8bf6fa8ddd791d9b09e7fc3b853fb00817969bfb
