### ISSUE TITLE
AO & AE OG Bug - Chanting on a controller can only be done with Speak I+II

### ISSUE THREAD

**Issue by pryon** [AliveTeam/alive_reversing#1170]
**Description of issue:** 
When the controller is the active input device, chanting can only be done when Speak I and Speak II are held, in both games.
As Speak I and Speak II were only meant to be bound to shoulder buttons, the user is very limited on the button layout they can use.

In the PSX builds of both games, any two shoulder buttons can be used to start chanting, be it Run+Sneak, Sneak+Speak2, etc.

**Steps to repro:** 
1. Set the controller as the active input device
2. Try chanting by holding Run + Sneak, Run + Speak I, etc.

**Comment by paulsapps** [comment]
fixed by #1246
