### ISSUE TITLE
Reversed game doesn't support AZERTY (and propably other keyboard layouts that aren't QWERTY)

### ISSUE THREAD

**Issue by UltraStars3000** [AliveTeam/alive_reversing#122]
**Found in build:** Probably never

**Description of issue:**
When pressing A on an AZERTY keyboard, the game will input Q, like a QWERTY. Same for others keys that are differently placed compared to a QWERTY keyboard layout.

**Steps to repro:**
Use an AZERTY keyboard, or just let me test :oddtism:

**Comment by d3nwah** [comment]
fix in #276
