### ISSUE TITLE
AO Rev Bug -  walking elum across paths crashes

### ISSUE THREAD

**Issue by seanparkerfilms** [AliveTeam/alive_reversing#1227]
Found in build: 1.0.3880.0

While in Paramonia, leaving this screen (photo attached) toward the left side exit while Elum is in "follow me" mode seems to cause a crash. I was able to repeat several times and the only way I made it work was by riding Elum to the left exit instead of walking with him.

This also happened if I returned to this screen from the next screen (by heading toward the right) while Elum was following.

Screen code is: F1P06C01 (I presume they are 1's... could be a capital I or lowercase L?)

![Screenshot 2021-04-09 141056](https://user-images.githubusercontent.com/82241488/114243157-f6a69100-9940-11eb-8dc0-3979d04c0f9e.png)

**Comment by mouzedrift** [comment]
crash caused by commit ba4d0ab1ff1de5a9c91c675a580da31b9ce150f0

**Comment by paulsapps** [comment]
probably gonna have to rework VOnPathTransition_401470 so it places elum correctly

**Comment by paulsapps** [comment]
[elumpath.zip](https://github.com/AliveTeam/alive_reversing/files/6409865/elumpath.zip)

repro save file, walk left without fix and then 💥
