### ISSUE TITLE
Sligs are sliding !

### ISSUE THREAD

**Issue by UltraStars3000** [AliveTeam/alive_reversing#128]
**Description of issue:**
Sligs are sliding without any animation and stops until they're slapped, or fall.

**Steps to repro:**
Quiksave at the last frame of the WalkingToStand animation, then quikload.
[Brewery Zulag 13.zip](https://github.com/AliveTeam/alive_reversing/files/3490529/Brewery.Zulag.13.zip)

**Function:** Slig::CreateFromSaveState_4B3B50

**Comment by UltraStars3000** [comment]
Fixed since build 1659 🚀

**Comment by paulsapps** [comment]
fixed in https://github.com/AliveTeam/alive_reversing/commit/801ee95d896b4a118873a0a4a9772734f0c7e150
