### ISSUE TITLE
Steamy Fleech death?

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#129]
Found in build: 1523
Last working build number: Don't know.

Description of issue: Fleeches seem to give off death steam at higher res or more opaqueness than normal or something... i dunno. Check out the footage: https://www.twitch.tv/videos/466118023

Steps to repro: using save file, just go hoist down the right edge of the top platform.
[steamy fleech scene.zip](https://github.com/AliveTeam/alive_reversing/files/3492114/steamy.fleech.scene.zip)

**Comment by UltraStars3000** [comment]
Confirmed fixed 🚀
