### ISSUE TITLE
AE Rev Bug - slog gets stuck turning left and right

### ISSUE THREAD

**Issue by paulsapps** [AliveTeam/alive_reversing#1295]
Found in build: [insert build number]
Last working build number: unknown

Description of issue:
Ask a slow to follow, he turns left and right forever.

Steps to repro:
In this screen:

![image](https://user-images.githubusercontent.com/7420121/117893765-f3415500-b2b2-11eb-9543-136251401e5d.png)

Get the slog to kill the slig, then ask the slow to follow while looking at him. He will keep turning left and right.

**Comment by mouzedrift** [comment]
coudlnt repro this issue but heres a save 
[!slogs.zip](https://github.com/AliveTeam/alive_reversing/files/6465863/slogs.zip)

**Comment by paulsapps** [comment]
Closing - can't seem to repro, they sometimes get stuck for a short while but that is OG
