### ISSUE TITLE
pressing F5 and then F6 within a short amount of time stores a quickload and it gets used when you press a key on your keyboard

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#13]
**Video:** https://streamable.com/7piw0

**Comment by mouzee1337** [comment]
this bug came with build 679.

**Comment by paulsapps** [comment]
I can only assume this must be related to SDL2 input handling as the change for that build was to enable SDL2 as the default renderer (but also input).

**Comment by paulsapps** [comment]
and uses himself after a movement = press any key - can't repro yet

**Comment by mouzedrift** [comment]
fixed 🚀
