### ISSUE TITLE
AO not starting on Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [AliveTeam/alive_reversing#1352]
with help here i have it compiled for what i can see correcly
when i start the game the launcher pops up so i can get to the dir with my game files that i got from GOG

when after that it crashes
here is my error that i get. im useing XINIT since my Pi build does not have a desktop

```
(zenity:21260): dbind-WARNING **: 19:09:42.085: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(zenity:21270): dbind-WARNING **: 19:09:51.163: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
/opt/retropie/ports/relive/relive-ao: line 41: relive: command not found
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.

```

**Comment by paulsapps** [comment]
What is `/opt/retropie/ports/relive/relive-ao` ? this isn't part of this repo it seems

**Comment by mouzedrift** [comment]
im pretty sure it's nemin's script which is located in the assets folder https://github.com/AliveTeam/alive_reversing/blob/master/assets/relive-ao

**Comment by Exarkuniv** [comment]
@paulsapps that is where in RetroPie. the binarys are placed to keep everything clean. 
if there are files or folders missing. i dont know. all i moved was the binary

**Comment by Nemin32** [comment]
You can manually set up relive-ao and relive-ae by 

1. Creating the following folders: `~/.config/relive-ao` and `~/.config/relive-ae` 
2. Creating a file in both of them called `install_folder`
3. Putting the game's location in these files, for instance `/home/your_name/.steam/steam/steamapps/common/Oddworld Abes Exoddus`

**Comment by Exarkuniv** [comment]
@Nemin32 i gave the manually setup for  relive-ao and relive-ae. it did not work
but using a script to run relive in the game folder works just fine.

thanks for your help

**Comment by Exarkuniv** [comment]
i have playing around with this for a bit and it seems to run really good on my Pi4
but when i played it on my computer i saw one thing different. 
My pi4 did not have any of the intro videos. 

is there a way to fix it. or it that the limitation of what it will do on a Linux OS due to drivers and what not.
