### ISSUE TITLE
CI Release Artifacts Are Totally Rekt m8 innit

### ISSUE THREAD

**Issue by d3nwah** [AliveTeam/alive_reversing#1363]
**Description of issue:** 
I'm having some issues with obtaining a working Release build of the project and help would be appreciated :) 

**Steps to repro:** 
1. Have a friend you want to recommend Abe's Oddysee to
2. Realize it probably won't run on their PC so be prepared to show them RELIVE
3. https://aliveteam.github.io/ the links to Windows builds don't work here
4. In appveyor there are only debug builds
5. Try to build it yourself, but get PSX_RECT in the process because there are some weird build problems related to libs (imgui.lib, reportedly invalid SDL2.dll file even after redownloading it, missing Exe.cpp files, easylogger++ linker issues etc.)
6. Decide to post a github issue instead.

**Save file:**
Couldn't obtain one

**Comment by paulsapps** [comment]
Release build works fine for me, post full repo steps + logs. CI builds debug because otherwise its very difficult to debug any crash dumps and the hook dlls won't function correctly in release. For the windows links we probably need a "latest build" link that will sometimes not work due to them being deleted and upload the last known good build + links to the website repo or something.

**Comment by d3nwah** [comment]
Worked around the issue by moving onto a non-Windows machine. I didn't have an issue building it on Linux, and currently have no easy means to reproduce it on Windows, having no Windows ready.

If it was just on my end, surely it won't happen if I or anyone else happen to build it from a clean state, so it's reasonable to close it.

If it wasn't just on my end, it will inevitably happen to someone else, and that person will probably make a more professional issue ticket than this one. Was supposed to be funny and meme'y, but it makes me cringe when I look at it now, so it's reasonable to close it.

Seeing both conditions result in a need to close it, closing it.
