### ISSUE TITLE
Publish relive binaries on github

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#1370]
currently https://aliveteam.github.io/ provides relive binaries by using appveyor builds but they get deleted every month so it might be worth publishing the relive binaries on github at the releases section so they dont get binned every month

**Comment by paulsapps** [comment]
https://github.com/AliveTeam/alive_reversing/releases/tag/appveyor_4227 can permalink to this and also link to the latest which may or may not get deleted
