### ISSUE TITLE
Abe fails to grab ledge when run jumping from afar, but succeeds when run jumping close up.

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#14]
[necrum ledge.zip](https://github.com/AliveTeam/alive_reversing/files/2706140/necrum.ledge.zip)

**Comment by mouzee1337** [comment]
its already fixed DansGame

**Comment by paulsapps** [comment]
Probably duplicate of #6

**Comment by mouzee1337** [comment]
> Probably duplicate of #6

yup can confirm
