### ISSUE TITLE
macOS - no config file

### ISSUE THREAD

**Issue by naymapl** [AliveTeam/alive_reversing#1443]
Hi. 
I build arm64 build on mac mini m1 and runing well the game (I checked Odysey and Exoddus) but have issue with 2 things - first where is any config file to change res for system one for ex 2560x1440 and other graphic settings. Secong things is game saves - i try to save the game progress but nothing working right now. Thank you for any help.

**Comment by paulsapps** [comment]
The internal resolution is hard coded and scaled to the window size currently. You can control aspect ratio and full screen with F11/12. 

https://github.com/AliveTeam/alive_reversing/blob/030cdc271174e2cc7c2af98492a4cb1b3077e679/Source/AliveLibAE/PauseMenu.cpp#L1201

Perhaps you can log or debug this to figure out why save doesn't work. You didn't provide much info on how it fails. It might be that the CWD isn't writable so the save fails.

**Comment by naymapl** [comment]
Ok - saves are working right now. I used quick save and this not working. Normal save working fine. But resolution stuck at 640x480/800x600. I try F11/F12 and change to fullscreen but res is still so low and game looks bad.

**Comment by paulsapps** [comment]
What do you mean by not working? Game crashes or what? :)

Can you post a screen shot of how it looks?

**Comment by naymapl** [comment]
Game is working but graphic is no scaling - its looks like dos game with 640px x 480px
<img width="1986" alt="Zrzut ekranu 2022-02-27 o 16 32 39" src="https://user-images.githubusercontent.com/24625283/155888915-f04df784-2390-474c-b382-0979c3e65a0e.png">

**Comment by paulsapps** [comment]
yeah that is as good as the game can look since that is the res of the assets

**Comment by naymapl** [comment]
Ok - so is no way to scalling this asset to higher res ? Some open ports are doing good job with old games and they looks much much better with orginal assets - for ex quake and doom ports, openmw, raze engine etc...

**Comment by paulsapps** [comment]
this isn't vector graphics so there is no way to add extra pixels to a 25x20 pixel sprite, upping the resolution doesn't add more detil
