### ISSUE TITLE
flying sligs dont shoot/chase abe

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#149]
**Found in build:** 1611

**Steps to repro:** load the save, go into the screen to the right and try to get chased by the flying slig o:

**Save:** [fslig.zip](https://github.com/AliveTeam/alive_reversing/files/3557168/fslig.zip)

**Cause:** FlyingSlig::AI_ChasingEnemy_4_435BC0

**Comment by paulsapps** [comment]
fixed? 🥇
