### ISSUE TITLE
Slogs go through wall collisions when falling

### ISSUE THREAD

**Issue by Sign-of-Exvil** [AliveTeam/alive_reversing#1495]
Found in build: 43529382
Last working build number: it works fine in the og game don't know about other builds.

Description of issue:
Slogs go through wall collisions when falling

Steps to repro:
https://drive.google.com/file/d/1LPl4SXqg33ABmxsYTPQSFZNNQjjvYOpW/view?usp=sharing
Just walk over one of the arrows and chant to wake slog.

**Comment by mouzedrift** [comment]
your google drive link isnt public so i cant access it

**Comment by Sign-of-Exvil** [comment]
ops should be fixed
