### ISSUE TITLE
Quiksaving followed by quikloading beneath screen with mines causes mines to despawn. They can be respawned by quiksaving and quikloading in any other screen OR by travelling away and coming back to the screen with the mines

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#15]
[no mines above.zip](https://github.com/AliveTeam/alive_reversing/files/2706146/no.mines.above.zip)

**Comment by paulsapps** [comment]
I have a feeling the bug is in creating the save.. and perhaps these save files are now busted and break even with OG?
