### ISSUE TITLE
AE Rev Bug - Saving with abe above slog, causes slog to not kill abe when loading

### ISSUE THREAD

**Issue by Sign-of-Exvil** [AliveTeam/alive_reversing#1523]
Found in build: 4542.
Last working build number: works in og game.

Description of issue:
Saving while abe is higher than a slog, (it seems to work better if the slog is standing below abe trying to get him, but it does work sometimes when he is moving towards abe), will make the slog run around abe and not kill him after loading (he can still kill/hit abe by jumping up or if abe is close to a wall).

Steps to repro:
Lvl link - https://drive.google.com/file/d/1Jh9P9mGhAOgoPLyTNDmVlSoAxZr2_KQZ/view?usp=sharing

1-attract slog.
2-quick save (as mentioned above, looks more consistent if slog is below abe, but it still seems to happen sometimes if quick saved while he is still moving towards abe).
3-quick load and jump down.

Demonstration vid link - https://drive.google.com/file/d/1MN7BdLuqStgMdyomoqy1m2YHoy36linF/view?usp=sharing

**Comment by mouzedrift** [comment]
fixed in #1524
