### ISSUE TITLE
AE Rev Bug - in slig barracks - block 4 - secret (2 mudokons). electric barriers don't get off after solving puzzle.

### ISSUE THREAD

**Issue by foldfree** [AliveTeam/alive_reversing#1542]
Found in build: build from source as in couple days ago (19th of june 2022)
Last working build number: no clue.

Description of issue:
in Slig Barracks Block 4, the secret area with 2 mudokons, there is a puzzle when you have to posses a flying slig and do a run avoinding bombs and lazers, at the end the lazers should turn off by themselves, it doesn't happen in the relive version. see video for expected behavior: https://youtu.be/t_aLxKSIgJk?t=26

Steps to repro:
here is the save when i finished the run with the flying slig but still have the lazer barriers activated.
[BAP14C05.sav.zip](https://github.com/AliveTeam/alive_reversing/files/8954921/BAP14C05.sav.zip)

**Comment by mouzedrift** [comment]
the electric walls are not supposed to turn themselves off. after you reach the end you have to pull the lever with the flying slig which was also done in the linked video.
