### ISSUE TITLE
AO - Crash after getting shot by a background slig on elum

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#1555]
https://clips.twitch.tv/UninterestedCrispyJuicePanicBasket-RGggzX2B7maxQvJy

unknown repro steps and if it's a relive or og bug

**Comment by NanobotZ** [comment]
Couldn't repro on OG.

Very easy to repro in Relive (freshly compiled from main branch):
1. Load save: [1555.zip](https://github.com/AliveTeam/alive_reversing/files/9238755/1555.zip)
2. Mount elum and get to the screen to the left, staying on the edge of it (z cover)
3. Wait for the bg slig to stop moving while he's facing Abe (important step)
4. Start running to the left and jump over the hole
(you can do this from the left side of the screen with the bg slig if you want, this way is just faster but I didn't have a 100% repro rate from the right for some reason, as seen on the video)

Interesting thing: if you let go of all buttons at the correct moment while getting shot, Abe can actually float in the air in the position he got shot, but pressing any move/gamespeak button just crashes the game.

Repro vid just in case:
https://user-images.githubusercontent.com/8195025/182284586-ebf22704-8852-4c87-af6a-e6f80f03aecf.mp4
