### ISSUE TITLE
AE & AO rev bug - Can't kill relive.

### ISSUE THREAD

**Issue by IogaMaster** [AliveTeam/alive_reversing#1574]
When I send SIGTERM (EDIT SIGINT) using CTRL-C in the terminal it does not close it just plays a sound. 
This is on linux.

**Comment by rozniak** [comment]
CTRL+C sends `SIGINT` - SDL by default catches `SIGINT` and `SIGTERM` and emits `SDL_QUIT` which should bring up the 'Do you really want to quit?' dialog.

We can change this behaviour using `SDL_HINT_NO_SIGNAL_HANDLERS`, but wondering does closing via the window manager generate a `SIGQUIT` or do they generate `SIGTERM` ? Ideally if the user presses the close button it should ask if they definitely want to quit. I'm not on Linux to test this atm - something to check later.

**Comment by IogaMaster** [comment]
I use a window manager and exiting the program sends the `kill` shell command. But it's does the same thing.

**Comment by rozniak** [comment]
What window manager is it?

**Comment by IogaMaster** [comment]
Sway

**Comment by IogaMaster** [comment]
It doesn't work on i3 either.

**Comment by rozniak** [comment]
Does it show the 'Do you really want to quit?' dialog at all ... ?

**Comment by IogaMaster** [comment]
No not at all

**Comment by rozniak** [comment]
@IogaMaster I have merged a potential fix, are you able to test on your machine?

**Comment by IogaMaster** [comment]
Yes, testing now

**Comment by IogaMaster** [comment]
It's fixed! Thank you.
