### ISSUE TITLE
240 Beta - Yellow "loading" mudokon icon doesn't appear

### ISSUE THREAD

**Issue by Mariogamer12** [AliveTeam/alive_reversing#1595]
Found in build: 240

Description of issue:
The Whatever That Makes The Screen Load Fade Thing Is A Black Bar Or Won't Appear

Steps to repro:
Go To The Next Screen

**Comment by mouzedrift** [comment]
fixed in e49f81ac039cd3b2c7f192772038814cefaf5d31
