### ISSUE TITLE
fleeches dont have the exact same behavior when chasing abe

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#191]
**Found in build:** 1738

**Description of issue:** the fleeches are supposed to "walk" against the slam door when abe stands behind it but they dont

**Steps to repro:** load the save and jump into the well

**Save:** [fleechtest.zip](https://github.com/AliveTeam/alive_reversing/files/3659710/fleechtest.zip)

**Function:** ``Fleech::AI_ChasingAbe_1_428760``

**Comment by d3nwah** [comment]
https://cdn.discordapp.com/attachments/533691351922114560/638114263755653151/Desktop_2019.10.27_-_21.37.33.01.mp4
(vid of OG)

Honestly, I'd leave it as is. The OG behaviour looks like a bug to me, while Rev behaviour seems perfectly reasonable
