### ISSUE TITLE
fleeches crash the game (pHoist was a nullptr)

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#197]
**Found in build:** 1762

**Steps to repro:** load the save and lure the fleeches to the left side, then run as fast as you can to the right screen and enter the well. (this method was pretty consistent for me but you might need a few trys)

**Save:** [fleechcrash.zip](https://github.com/AliveTeam/alive_reversing/files/3668146/fleechcrash.zip)

**Comment by UltraStars3000** [comment]
**Function :** Fleech::AI_Patrol_0_430BA0

**Comment by d3nwah** [comment]
**Function** : Fleech::AI_ChasingAbe_1_428760()
