### ISSUE TITLE
Abe acts as if door is closed when trying to enter door offscreen.

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#198]
Latest build - Bugged function: IsOpenDoorInRange_44EE10

Issue: Abe won't enter a door whilst offscreen. In OG, he is able to.

Steps to repro: Load savefile, wait atleast 3 seconds, then try entering door. Bug is that Abe acts as if door is closed (he shrugs). *Note: You won't be able to see Abe as he is offscreen.*

[door bug gib.zip](https://github.com/AliveTeam/alive_reversing/files/3668152/door.bug.gib.zip)

Function at Fault: IsOpenDoorInRange_44EE10

**Comment by paulsapps** [comment]
is fixed?
