### ISSUE TITLE
'Slig in adjacent screen' SFX cannot be heard.

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#20]
In the very first screen of the game, you are meant to hear adjacent screen slig walking SFX. No SFX can be heard.

The same applies to the first screen of tunnel 2, where you are supposed to hear the same SFX of a slig walking in an adjacent screen, but it doesn't sound.

(in case you dont know, the sound is merely cosmetic. The slig doesn't actually exist until you enter the screen that it can be found in)

**Comment by AvengingGibbons** [comment]
And now I AM hearing the SFX, but it's persisting no matter which screen i go to...

**Comment by mouzee1337** [comment]
i took a quick look and it looks like pausing and unpausing the game stops the slig SFX and not restart path

**Comment by mouzee1337** [comment]
build 297 added the bug.
https://ci.appveyor.com/project/paulsapps/alive-reversing/builds/17943504/job/r2ob6kb9u5u1ebgp/artifacts

**Comment by mouzee1337** [comment]
looks like SND_Clear_4CB4B0 causes the bug

**Comment by paulsapps** [comment]
I wrongly assumed the data in there was never used, but it actually is as a pointer to unk_BB3078 is taken which leads to reads from dword_BB3080 and beyond

**Comment by paulsapps** [comment]
Please verify fix :100:

**Comment by mouzee1337** [comment]
fixed 💯
