### ISSUE TITLE
Crash possibly related to sloggies or slogs. Ask gibbons to do the non-glitched mehod in the 2-parter zulag in hub 1...

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#200]
No detail coz im in bed on my phone. Bug posted just for sake of not forgetting about it.

Issue: Game crash when releasing the sloggies, run-jumping to the left, then crash occurs as I run-jump back towards the right ledge as the last couple sloggies have just ran off the ledge. (Abe is maybe in middle of jump when crash happens so not in full contact with slogs.. but I’ll have to repro to know for sure.

**Comment by mouzedrift** [comment]
**Save:** [mlg's pets.zip](https://github.com/AliveTeam/alive_reversing/files/3668216/sloggies.zip)

just stand still and the game will crash soon™️

**Comment by UltraStars3000** [comment]
**Function :** Slog::FindTarget_4C33C0

**Comment by mouzedrift** [comment]
fixed pls close :oddtism:
