### ISSUE TITLE
slogs run randomly away when chasing abe

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#207]
**Found in build:** 1784

**Steps to repro:** load the save and... uh ... wait lol

**Save:** https://github.com/AliveTeam/alive_reversing/files/3668216/sloggies.zip

**Function:** ``Slog::FindTarget_4C33C0``

**Comment by d3nwah** [comment]
Fixed in https://github.com/AliveTeam/alive_reversing/pull/254
