### ISSUE TITLE
Trying to enter closed door by holding down up button makes Abe continue to try to enter door.

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#210]
**Build Number:** 1784

Stand in front of closed door and hold 'up' indefinitely. Abe repeatedly attempts to enter door. He should only attempt once, and then will enter immediately as soon as door opens if player is still holding up when it opens.

[door entry try bug.zip](https://github.com/AliveTeam/alive_reversing/files/3694374/door.entry.try.bug.zip)

**Function:** Abe::State_0_Idle_44EEB0

**Comment by mouzedrift** [comment]
**Save:** [closeddoor.zip](https://github.com/AliveTeam/alive_reversing/files/3694386/closeddoor.zip)

**Function:** ``Abe::State_0_Idle_44EEB0``
