### ISSUE TITLE
Paramites collide with falling rock when standing on edge of ledge. In OG theyre safe even though the rock appears to hit them.

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#211]
1784

Description of Issue: (see title)

walk up to edge of ledge and stand there. Falling boulder kills paramite but it shouldnt when standing on the edge.

[paramit boulder coli.zip](https://github.com/AliveTeam/alive_reversing/files/3694414/paramit.boulder.coli.zip)

**Function:** mouze help

**Comment by mouzedrift** [comment]
**Function:** ``FallingItem::DamageHitItems_427F40``
