### ISSUE TITLE
Demo playback is different than OG behaviour

### ISSUE THREAD

**Issue by d3nwah** [AliveTeam/alive_reversing#214]
**Found in build:** 
21c408727ea56a1764b4e72ba8d0e9f9eb641610
**Description of issue:** 
Demo playback is different than OG behaviour, as if the game read the inputs wrongly. Issue occurs in multiple demos, for example "Mudokons 2" or "Fart-a-poppin'" 
**Steps to repro:** 
1. Main menu
2. Options.
3. Demos.
4. "Fart-a-poppin'" 
5. Observe the mayhem

**Comment by paulsapps** [comment]
"Farts-a-poppin'" is more than  Abe::State_89_BrewMachineBegin_4584C0. :(

**Comment by d3nwah** [comment]
Explosion::DealBlastDamage_4A1BD0()

**Comment by d3nwah** [comment]
fixed in #274

what wasn't fixed reported in #273
