### ISSUE TITLE
Rev Bug MIP02C27 (Secret jingle too quiet)

### ISSUE THREAD

**Issue by Varrok** [AliveTeam/alive_reversing#219]
**Found in build:** 
4d331dba970622ce155b9c416d66345fd170c3e2
**Description of issue:** 
Secret jingle too quiet under MIP02C27. Possibly happening in more places.
**Steps to repro:** 
1. Be in MIP02C27.
2. Jump down (doesn't matter if you die. It's a cruel world)
3. There should be a relatively loud secret area jingle in the cam below, but it's hardly audible
**Save:** 
[MIP02C27.zip](https://github.com/AliveTeam/alive_reversing/files/3704556/MIP02C27.zip)

**Comment by Varrok** [comment]
It was something on my end, combined with the weirdness of the game's music system.

**Comment by paulsapps** [comment]
USER ERROR!
