### ISSUE TITLE
Slig panic turn function bug

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#222]
**Found in build:** 1797

**Description of Issue:** Dunno how to describe this well... the slig should complete a panic turn before stopping to shoot abe, but the slig aborts the last part of the turn animation, and shoots abe.

**Steps to repro:** i wont bother explaining :LUL:

**Save:** repro is too tricky for you, paul :shook:

**Function:** AI_PanicTurning_12_4BC490

**Comment by paulsapps** [comment]
[keeprunning.zip](https://github.com/AliveTeam/alive_reversing/files/3722022/keeprunning.zip)

Adding save file because Gibbons is rubbish. For future repro if it regresses. Load save and if you don't get shot its bugged.
