### ISSUE TITLE
some text in the pause menu load section is missing

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#226]
**Found in build:** 1804

**Steps to repro:** start the game and take a look at the pause menu load section

**Function:** ``PauseMenu::Page_Main_Update_4903E0``

# reversed
![Exoddus_NoStubs_hPa0Ni2u3I](https://user-images.githubusercontent.com/43358824/66767887-ab2d3700-eeb1-11e9-8b66-a9ce95a28442.png)
# OG
![Exoddus_ScdxhrEsb7](https://user-images.githubusercontent.com/43358824/66767909-b1231800-eeb1-11e9-9eef-9c793e403155.png)
(dont mind my german OG game lul)

**Comment by paulsapps** [comment]
![image](https://user-images.githubusercontent.com/7420121/67810763-17ec2800-fa93-11e9-96d1-7a045806e4fd.png)

English text for ref

**Comment by mouzedrift** [comment]
💪 fixed
