### ISSUE TITLE
Missing SFX on main menu when going back to it after loading a level

### ISSUE THREAD

**Issue by UltraStars3000** [AliveTeam/alive_reversing#23]
**Found by MarioMuzic**

`How to reproduce it:`
1)If you're starting the game from the debug save file, delete it. You need to start the game from menu.
2)Load a level (via save file or starting from Mines)
3)Go back to main menu

And you'll notice that there is some SFX that is missing on it. (Mario and myself have tried it)

**Comment by mlgthatsme** [comment]
Hey @UltraStars3000,

I wasn't able to reproduce the bug with the steps you mentioned.
Can you confirm the issue is still present in the latest build?

**Comment by UltraStars3000** [comment]
[2019-01-14 21-32-29.zip](https://github.com/AliveTeam/alive_reversing/files/2756936/2019-01-14.21-32-29.zip)
Still present in build 810.

**Comment by mouzee1337** [comment]
i do like to mention that the bird chirps are missing in general so that is the reason why it doesnt play when going back into the menu 💯

**Comment by mouzee1337** [comment]
the bug came with build 223.

**Comment by mouzee1337** [comment]
build 812 fixed it 👍
