### ISSUE TITLE
Non-standalone version is now ignoring abe2.ini

### ISSUE THREAD

**Issue by UltraStars3000** [AliveTeam/alive_reversing#24]
The title says everything.
Custom controls from abe2.ini won't be used the game will use default ones.

**Comment by mouzee1337** [comment]
> The title says everything.
> Custom controls from abe2.ini won't be used the game will use default ones.

am i retarded or smth? the abe2.ini configs did nothing for me tho LUL

**Comment by mlgthatsme** [comment]
abe2.ini should now load the key bindings correctly as of 78a2be5 .
