### ISSUE TITLE
Rev bug - Double tapping arrows makes Abe run

### ISSUE THREAD

**Issue by d3nwah** [AliveTeam/alive_reversing#250]
not OG behaviour

**Comment by d3nwah** [comment]
Additional information:

Turns out issue is related to Controller support, repro steps should be as follows:
- plug gamepad
- set up gamepad (so it's selected as controller in Controller menu)
- load game, check if it works
- close game
- unplug gamepad
- launch game
- load game (don't change options - gamepad will still be selected as Controller, but the game lets you use keyboard)
- notice double tapping makes Abe run
- ???

**Comment by UltraStars3000** [comment]
**Function :** Input::Input_InitJoyStick_460080
