### ISSUE TITLE
OG Bug - Abe attempts slapping mudokons out of reach

### ISSUE THREAD

**Issue by d3nwah** [AliveTeam/alive_reversing#266]
**Description of issue:** 
https://cdn.discordapp.com/attachments/309087612419833866/638799858135728148/Desktop_2019.10.29_-_19.01.41.04.mp4
Abe attempts slapping mudokons out of reach instead of just going "Grrr"

[slapAir.zip](https://github.com/AliveTeam/alive_reversing/files/3785090/slapAir.zip)

**Steps to repro:** 
-Be in the position on the leftmost of the screen
-Try angry gamespeak
-Slap instead

**Comment by paulsapps** [comment]
I think this a feature but ;D

**Comment by d3nwah** [comment]
> I think this a feature but ;D
No messing around, or you get a slap!

**Comment by d3nwah** [comment]
Maybe that is a feature after all
