### ISSUE TITLE
sligs without pants dont spawn (block 3)

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#27]
Found in build: 810

**Description of issue**:
sligs without pants dont spawn if you enter the left screen first(they spawn if you visit the right screen first)

**Steps to repro**:
load the save file and go to the left screen

[save.zip](https://github.com/AliveTeam/alive_reversing/files/2755897/save.zip)

**Comment by paulsapps** [comment]
Confirmed same issue
