### ISSUE TITLE
shrykulls "attack" has the wrong color 

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#28]
**Found in build**: 811

**Description of issue**:
shrykulls "attack" has the wrong color 

https://cdn.discordapp.com/attachments/505078398087987201/534458895414853642/2019-01-14_20-02-59.mp4
this bug came with build 372.

**Comment by paulsapps** [comment]
Bug must be in PSX_EMU_Render_SPRT_4bit_51F0E0

**Comment by mouzee1337** [comment]
i fogot to add the save file...
**save file**:
[shrykull.zip](https://github.com/AliveTeam/alive_reversing/files/2766287/shrykull.zip)

**Comment by mouzedrift** [comment]
fixed 🚀
