### ISSUE TITLE
Rev Bug - border pixels are borked

### ISSUE THREAD

**Issue by d3nwah** [AliveTeam/alive_reversing#280]
Found in build: current
Last working build number: probably never

Description of issue:
The pixel lines at the render area top, bottom and left part are borked

![image](https://user-images.githubusercontent.com/6751254/68070784-2f693080-fd73-11e9-8b6c-4e2bd0b5b58a.png)

**Comment by paulsapps** [comment]
probably same as #71

**Comment by mouzedrift** [comment]
fixed on the abi break branch
