### ISSUE TITLE
Rev save crashes OG but not Rev

### ISSUE THREAD

**Issue by d3nwah** [AliveTeam/alive_reversing#295]
Found in build: Current one
Last working build number: Presumably never

Description of issue:
A savegame made in Reversed game (dll) crashes OG but not Rev.

Steps to repro:
[SaveGame.zip](https://github.com/AliveTeam/alive_reversing/files/3832536/SaveGame.zip)

**Comment by paulsapps** [comment]
OG avoids crash because it calls RunTests which somehow prevents looking up object id 0 returning ResourceManager*. But root cause is that Rev has created a bad save because ID 0 shouldn't be saved in there for field 120.

**Comment by paulsapps** [comment]
pls verify

**Comment by d3nwah** [comment]
Issue still occurs in current master revision
