### ISSUE TITLE
deactivated UXB mine activates itself if you go too far away (3 screens)

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#30]
**Found in build**: 812

**Description of issue**:
deactivated UXB mine activates itself if you go too far away (3 screens)

**Steps to repro**:
start the game from the beginning, use cheats and go 2 screens to the right, deactivate the UXB mine and then go 3 screens from the UXB mine away (try the right side)

**bug has been added with build**: 554
https://ci.appveyor.com/project/paulsapps/alive-reversing/builds/20380342/job/hs8l2hppdy6jm9rv/artifacts

**Comment by mouzee1337** [comment]
fixed

**Comment by paulsapps** [comment]
Assuming fixed in 1.0.819, closing
