### ISSUE TITLE
file part not found crash

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#31]
**Description of issue**:
file part not found crash 
its random and happens in all builds

https://cdn.discordapp.com/attachments/505078398087987201/534844800260767784/unknown.png
**Steps to repro**:
happens randomly when loading a quicksave

**Comment by paulsapps** [comment]
Possibly also caused by #15

**Comment by paulsapps** [comment]
This might have been fixed since the game now uses blocking I/O on windows. I didn't realise it was still using win32 async I/O.

**Comment by mouzedrift** [comment]
fixed? 💯 i cant repro it anymore
