### ISSUE TITLE
game crash when you quiksave and quikload while the death gas is filling the screen

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#312]
**Found in build:** 1970

**Steps to repro:**
1) load the save
2) kill the glukkon
3) wait for the death gas
4) quiksave and quikload

**Save:** [deathgas.zip](https://github.com/AliveTeam/alive_reversing/files/3871038/deathgas.zip)

**Comment by UltraStars3000** [comment]
**Function:** `GasCountDown::ctor_417010`
