### ISSUE TITLE
glitching blood sprites

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#319]
Found in build: 2000

Steps to repro:
1) load the save
2) give the slogs bones to eat or offer your own bones
3) look if the blood sprites are glitchy

Save: https://cdn.discordapp.com/attachments/505078398087987201/657269774698414080/slogs.sav

if the sprites dont glitch at the first try try to quikload a few times and try again

**Comment by UltraStars3000** [comment]
**Function:** `PSX_EMU_Render_SPRT_4bit_51F0E0`

**Comment by paulsapps** [comment]
Happens more often in AO and looks worse in AO, also happens to explosions in AO.

**Comment by mouzedrift** [comment]
should be fixed on the abi break branch
