### ISSUE TITLE
multiple lifts at the same position

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#32]
**Found in build**: 932

**Description of issue**:
there are multiple lifts at the same position under/above other lifts where they are not supposed to be.

**Steps to repro**:
rescue the mudokon and  look if there is a second lift under your current screen

**save**: [lift 2.zip](https://github.com/AliveTeam/alive_reversing/files/2881085/lift.2.zip)

**cause**: Factory_LiftPoint_4D7250

**Comment by paulsapps** [comment]
Fixed in 934
