### ISSUE TITLE
well shoots you out of the map

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#33]
**Found in build**: 943

**Description of issue**:
the well shoots you out of the map and crashes your game

**Steps to repro**:
load the save and enter the well
[enter well.zip](https://github.com/AliveTeam/alive_reversing/files/2894716/enter.well.zip)

**cause**: State_79_Inside_Of_A_Well_Local_45CA60

**Comment by mouzee1337** [comment]
[well saves.zip](https://github.com/AliveTeam/alive_reversing/files/2895511/well.saves.zip)

uploaded some saves with different well positions since it affects all wells

**Comment by mouzee1337** [comment]
fixed

**Comment by paulsapps** [comment]
💯
