### ISSUE TITLE
the letter "H" of the word "THIS" is missing colors partly on the LCD screen on camera MIP04C11

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#337]
just load the save and wait for the word "THIS"

**Save:** 
[lcd screen bug.zip](https://github.com/AliveTeam/alive_reversing/files/4087150/lcd.screen.bug.zip)

![unknown](https://user-images.githubusercontent.com/43358824/72743795-a06af800-3bac-11ea-98cc-5e657a5aeda2.png)

i couldnt repro this at different locations

**Comment by UltraStars3000** [comment]
**Function:** `PsxRender::PSX_Render_PolyFT4_8bit_SemiTrans_501B00`

**Comment by rozniak** [comment]
Fixed in upcoming OpenGL renderer
