### ISSUE TITLE
deleting saves in the pause menu causes the save at the bottom of the list to be visually "duplicated"

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#340]

**Comment by UltraStars3000** [comment]
`PauseMenu::Page_Load_Render_4910A0` & `PauseMenu::Page_Load_Update_490D50` are the only function that has an impact on the load menu, but :
-Disabling `PauseMenu::Page_Load_Render_4910A0` is making all the saves invisible.
-`PauseMenu::Page_Load_Update_490D50` isn't the cause of the issue.

**So my guess is that `PauseMenu::Page_Load_Render_4910A0` is the function in cause in this issue.**
