### ISSUE TITLE
stack-buffer-underflow on address 0x7fff703fd0d0 at pc 0x557deffcccf7 bp 0x7fff703fcfd0 sp 0x7fff703fcfc8

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#353]
check [this](https://gist.github.com/mouzedrift/8ae2c19c5fc6d72a8244f1eef988c208) for more details.

**Comment by paulsapps** [comment]
is this still happening @mouzedrift  ?

**Comment by mouzedrift** [comment]
dunno didn't test this again and i would've to set up everything again :tape:

**Comment by mouzedrift** [comment]
tracking those issues with #1051 now
