### ISSUE TITLE
going through a teleporter with invisibility causes abe to not fade away

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#36]
**Found in build**: 952

**Description of issue**:
abe doesnt fade away if he goes through portals with invisibility.
this is what i mean with "fading away" 
**edit**: its supposed to look like this and if it doesnt then its wrong
![exoddus_8fs3o3vjr1](https://user-images.githubusercontent.com/43358824/53302591-e108a700-385f-11e9-935e-fb17082f71ed.png)

**Steps to repro**:
load the save file and go into the teleporter before the invisibility fades away.

**save**: [teleporter test.zip](https://github.com/AliveTeam/alive_reversing/files/2898145/teleporter.test.zip)

**cause**: ctor_4228D0

**Comment by paulsapps** [comment]
RingSpark issue was in vUpdate_4DC400

**Comment by mouzee1337** [comment]
fixed 💯
