### ISSUE TITLE
Evilfart doesn't explode while zapped

### ISSUE THREAD

**Issue by d3nwah** [AliveTeam/alive_reversing#363]
Found in build: master  97f0a337204b0f18974771d9ef6ec16ce11ddb97
Last working build number: presumably never

Description of issue:
Evilfart doesn't explode while zapped. It just gets purple, making me feel blue.

Steps to repro:
Fly with a fart through a zapfield
![image](https://user-images.githubusercontent.com/6751254/79800295-3d7c2f00-835c-11ea-824f-e7a1055ac49e.png)

**Comment by d3nwah** [comment]
[handy_savegame.zip](https://github.com/AliveTeam/alive_reversing/files/4506202/handy_savegame.zip)

**Comment by mouzedrift** [comment]
**Function:** ``EvilFart::vUpdate_423100``
