### ISSUE TITLE
FMV playback speed issue

### ISSUE THREAD

**Issue by d3nwah** [AliveTeam/alive_reversing#365]
Found in build: 97f0a337204b0f18974771d9ef6ec16ce11ddb97 DLL and Standalone
Last working build number: not found as of yet

Description of issue:
https://cdn.discordapp.com/attachments/505078398087987201/701905593849479278/video.mp4
All the fmvs start with a few seconds lag, then are crazy fast to compensate

Steps to repro:
No clue. Works fine on other computers

**Comment by d3nwah** [comment]
No longer happening as of 95aacb266cc7222ac64066dca1bed5d8dac42bd8 . Will reopen if happens again

**Comment by paulsapps** [comment]
does it always repro before this change?

**Comment by d3nwah** [comment]
yes, it did. I don't know if this specific commit fixed it, **if** it was a commit or just something I happened to change on my end

**Comment by paulsapps** [comment]
I mean if you reset to 1 before the mentioned comment does it still repro on your current setup?
