### ISSUE TITLE
Missing foreground layers

### ISSUE THREAD

**Issue by UltraStars3000** [AliveTeam/alive_reversing#369]
**Description of issue:**
Missing foreground layer when in background in Mudanchee Ender, and probably more places

**Steps to repro:**
-Start a game, or load a save that isn't in Mudanchee Ender path.
-Use `Level select` through Pause Menu's Developer mode and select `Mudanchee Vaults Ender`
-Now foreground layers should be messed up.

**Comment by paulsapps** [comment]
Probably issue with the hacky dev level select menu - I don't think it puts abe in the correct scale/layer

**Comment by mouzedrift** [comment]
^ could probably close the issue or remove it from the reimpl bug list

**Comment by mouzedrift** [comment]
the developer menu has been removed on the new `abi_break_refcount` branch so this can no longer happen
