### ISSUE TITLE
AO Rev Bug - PullRingRope is too long

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#443]
OG vs rev:
![unknown](https://user-images.githubusercontent.com/43358824/86537443-60e06000-beef-11ea-93b6-4f6a4a749d25.png)

Steps to repro:
- load the save
- go two screen to the right 
- 👀 

Save: 
[PullRingRope.zip](https://github.com/AliveTeam/alive_reversing/files/4875279/PullRingRope.zip)

Function: PullRingRope::ctor_4546B0

**Comment by paulsapps** [comment]
#445 should fix this
