### ISSUE TITLE
abe can go through a slam door without hitting it with ddcheat

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#47]
**Found in build**: 990

**Description of issue**:
abe can go through a slam door without hitting it with ddcheat but hes supposed to hit it with ddcheat

- you shall not pass

**Steps to repro**:
use the ddcheat, go to a slam door and try to go through 

**cause**: ctor_4AF700

**Comment by mlgthatsme** [comment]
This happens in the exe only because **ClearInsideSlamDoor_4B0530** is not implemented.

Once this is done the issue should be resolved.

**Comment by mlgthatsme** [comment]
@mouzee1337 Please confirm the issue is resolved?
