### ISSUE TITLE
there are too many particle burst effects for explosions

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#49]
**Found in build**: 1007

**Description of issue**:
there are too many particle burst effects for explosions.
also 6 particles for each explosions looks like the default value to me.

**Steps to repro**:
load the save file and shot lul

**save**: 
[particles.zip](https://github.com/AliveTeam/alive_reversing/files/2949962/particles.zip)

**cause**: ctor_41CF50

**Comment by paulsapps** [comment]
Hmm seems the same on and off to me.. maybe already fixed? 🥇

**Comment by paulsapps** [comment]
Somehow I was looking at explosion ctor not particle burst ctor 😂

**Comment by mouzee1337** [comment]
when you already know that the ctor is the cause but the function isnt implemented yet AbeCreep

**Comment by paulsapps** [comment]
ParticleBurst::ctor_41CF50 is implemented 💃

**Comment by mouzee1337** [comment]
so am i Kappa

**Comment by mouzee1337** [comment]
fixed 🚀
