### ISSUE TITLE
AO Rev Bug - There's some weird distortion when you ring the bells

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#494]
Steps to repro:
- load the save
- enter the screen to your right
- possess the chime ball
- press the left arrow key

## REV🥈 vs OG🥇  

| REV | OG |
| ---- | ---- |
| ![AbeWin_AliveDllAO_rO910GuvMG](https://user-images.githubusercontent.com/43358824/88119652-69a88580-cbc1-11ea-8ba5-3d8747e7e1d5.png) | ![AbeWin_oQk8j71Mad](https://user-images.githubusercontent.com/43358824/88119688-7dec8280-cbc1-11ea-9e51-3733ea08c23b.png) |

Save: 
[bells.zip](https://github.com/AliveTeam/alive_reversing/files/4957071/bells.zip)

Function: WinMain::Game_Main_450050

**Comment by paulsapps** [comment]
This might be caused by the compatibility settings so if anyone else attempts to fix this bear that in mind.

**Comment by mouzedrift** [comment]
fixed :oddtism:
