### ISSUE TITLE
AO Rev Bug - Meat disappears/(lands elsewhere?) when you throw it into the left or right screen

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#535]
Steps to repro:
- load the save
- head to the left until you find a meat sack
- get meat
- throw it into the screen to your right

Save: 
[rolling ball.zip](https://github.com/AliveTeam/alive_reversing/files/5013098/rolling.ball.zip)

Function: RollingBall::sub_418590

**Comment by paulsapps** [comment]
disabled that func for now because :NightmareAbe:
