### ISSUE TITLE
blackscreen for a frame or so when you go through doors/wells with cinematic animations

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#55]
**Found in build**: 1055

**Steps to repro**: enter the first secret of the game and go through the door

**the bug came with those changes**: https://github.com/AliveTeam/alive_reversing/commit/983b8a8141f847361d6f9fb7abdaf1c43ea3953e

**Comment by paulsapps** [comment]
btw this code also leaks @mlgthatsme

**Comment by mlgthatsme** [comment]
leak + black screen fixed now.

**Comment by paulsapps** [comment]
Don't you need to also handle the case where the width/height changes? Your cached texture will still be using the old width/height in that case.
