### ISSUE TITLE
the game sound interrupts randomly

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#56]
**Found in build**: 1055

i would say it came with this: https://github.com/AliveTeam/alive_reversing/commit/7ef52630a3c2c10bfa790e14e8f39ad8d4971ec1

but im not sure

**Comment by mlgthatsme** [comment]
do you have any recordings of this happening?

**Comment by paulsapps** [comment]
@mouzedrift is this still an issue in latest?

**Comment by paulsapps** [comment]
@mouzedrift still a bug? or close this?

**Comment by mouzedrift** [comment]
yeah i dont think i still have this
