### ISSUE TITLE
weirdo ledge bug

### ISSUE THREAD

**Issue by mouzee1337** [AliveTeam/alive_reversing#6]
i mean that ledge at 0:18 is obvious isnt it? :tapeDan:
https://cdn.discordapp.com/attachments/505078398087987201/526367018287366169/2018-12-23_12-51-34.mp4

**Comment by paulsapps** [comment]
[ledge_bug.zip](https://github.com/AliveTeam/alive_reversing/files/2706065/ledge_bug.zip)
