### ISSUE TITLE
AO OG Bug - Some controls get blank if a certain key is assigned to them.

### ISSUE THREAD

**Issue by UltraStars3000** [AliveTeam/alive_reversing#612]
**Description of issue:** Setting some keys to a control can lead them to get blank when you restart the game. Then you can't use that action until you set the key again.

**Steps to repro:** Set G to Action.
Restart the game.
Notice it.

Note that on French version, G works for Action. Might be worth checking for others.

**Comment by paulsapps** [comment]
@UltraStars3000  / @pryon  could you check if this is now fixed?

**Comment by paulsapps** [comment]
@UltraStars3000 confirmed fix
