### ISSUE TITLE
mudokon turns away from abe instead of facing abe if you call multiple mudokons in the same screen

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#63]
**Found in build**: 1130

**Steps to repro**: go into a screen with multiple mudokons and call everyone at once

**comparison video**: https://cdn.discordapp.com/attachments/505078398087987201/567831764425375902/2019-04-16_23-59-47.mp4

**cause**: AI_Wired_4_477B40

**Comment by mouzedrift** [comment]
still not fixed FeelsBadMan

**Comment by paulsapps** [comment]
But actually it probably is? 🥇

**Comment by mouzedrift** [comment]
indeed
still not 100% the same but it needs fixing later since this is also an OG bug.
dont care too much yet i suppose 🥇
