### ISSUE TITLE
AE Rev Bug - Can't bind fart/roll input on gamepad

### ISSUE THREAD

**Issue by Fatwanker** [AliveTeam/alive_reversing#706]
Found in build: f0d50f4
Last working build number: N/A

Description of issue:
Failure to successfully rebind Fart/Roll command in options menu using Xbox One gamepad. Rebinding it to "A" automatically rebinds it to "Y" and prevents the use of the A button entirely.

Steps to repro:
Connect controller of choice
Open AliveExeAE
Navigate to Options > Controls
Highlight "Game Pad" and press "C" to configure
Rebind any commands as you see fit
Check Fart/Roll command (Should be "A" for Xbox controllers, or "X" for Playstation)
Attempt to rebind to another input.

**Comment by pryon** [comment]
One half of this - preventing the use of the <kbd>X</kbd> and <kbd>A</kbd> controller inputs in the menu after binding them to something - is fixed in #772, the other half is an OG bug that is tracked in #790.

As such, this issue can be closed IMO.

**Comment by pryon** [comment]
Welp, turns out I was wrong, fixing #790 won't fix this, there is indeed a particular bug only affecting the fart/roll command on gamepad. I'll investigate further.
