### ISSUE TITLE
abe gets a bit cut off if you stay between 2 screens (only the right side)

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#71]
**Found in build**: 1162

**save**: 
[render.zip](https://github.com/AliveTeam/alive_reversing/files/3167999/render.zip)

**cause**: PSX_Render_PolyFT4_8bit_SemiTrans_501B00

**Comment by paulsapps** [comment]
check if removing

```
    if ( (xpos_clip % 2) !=0)
    {
        // TODO: HACK HACK, some xpos rendering is off by 1
        pVramDst = pVramDst - 1;
    }
```

seems ok? I can't find out why this hack is here

**Comment by d3nwah** [comment]
> check if removing
> 
> ```
>     if ( (xpos_clip % 2) !=0)
>     {
>         // TODO: HACK HACK, some xpos rendering is off by 1
>         pVramDst = pVramDst - 1;
>     }
> ```
> 
> seems ok? I can't find out why this hack is here

Commenting this out seems to be fixing this for me. Dunno about side effects, if there are any

**Comment by d3nwah** [comment]
Levers during screen transitions are also affected by the hack (wrong offset while hack is on)

**Comment by mouzedrift** [comment]
fixed on the abi break branch
