### ISSUE TITLE
Door issue

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#76]
I just wrote all this out and now it's disappeared fml...

When entering a screen with doors that have an initial state 'closed' they begin open and do a door closing animation immediately.
[door issue.zip](https://github.com/AliveTeam/alive_reversing/files/3244156/door.issue.zip)

**Comment by mouzedrift** [comment]
its identical to the OG game so the issue can be closed

**Comment by paulsapps** [comment]
:Oddtism: !
