### ISSUE TITLE
Scrab fight is fucked.

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#77]
Found in build: Current build.
Last working build number: No clue.

Description of issue: When the scrabs run at each other and meet during a fight, one disappears as they collide and the other is stuck in a stationary running animation. Theyre supposed to spin with each other.
[scrb fight new strat.zip](https://github.com/AliveTeam/alive_reversing/files/3244188/scrb.fight.new.strat.zip)

Steps to repro:
[insert repro steps, please also attach a save file too where possible]

**Comment by paulsapps** [comment]
seems to be caused by  Scrab::vUpdate_4A3530
