### ISSUE TITLE
AE OG Bug - One input can be bound to multiple controls

### ISSUE THREAD

**Issue by pryon** [AliveTeam/alive_reversing#790]
**Description of issue:** 
In the `Options` -> `Controls` menu, you can bind a single input (e.g. <kbd>X</kbd> on the keyboard or <kbd>Y</kbd> on an XInput controller) to an arbitrary amount of controls, even all of them:
![image](https://user-images.githubusercontent.com/12021392/96911024-9447fa00-14a0-11eb-9c0f-8aa4d352c218.png)

This is how it also gets saved into the ini:
```
[Control Layout]
controller = Keyboard

[Keyboard]
run = X
sneak = X
jump = X
action = X
throw = X
fart = X
```

It applies to both the gamepad and the keyboard configs as well.

In-game it's always the *jump* control that is taking effect when pressing the single key that has been bound to everything.

**Expected behavior:**
When you remap a key to another control, the key's original mapping should be reset to blank.

**Steps to repro:** 
 - Go to `Options` -> `Controls`
 - Make sure the cursor is blinking on `Keyboard` and press <kbd>C</kbd> to reconfigure
 - Map all controls to the key <kbd>X</kbd>
 - Start up a new playthrough and try doing anything besides jumping and walking

**Comment by paulsapps** [comment]
Probably no reason not to fix this one now since it isn't game play behaviour change
