### ISSUE TITLE
Spark graphical effect from bonedrills cause blue line artifacts

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#8]
[blue line artifacts.zip](https://github.com/AliveTeam/alive_reversing/files/2706116/blue.line.artifacts.zip)

**Comment by paulsapps** [comment]
renamed sfx to graphical effect to avoid confusion with SFX for sound effect thats in the 2 other open issues :key:

**Comment by mouzee1337** [comment]
this bug came with build 445, check it

**Comment by mouzee1337** [comment]
PSX_Clip_LineSegment_Against_DrawEnv_4FE640 should be the cause

**Comment by mouzee1337** [comment]
fixed 👍
