### ISSUE TITLE
AO Rev Bug - Chime lock ball moves on its own

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#824]
Steps to repro:
- load the save
- go into the screen to your right
- possess the chime lock
- 👂👀 

save:
[!.zip](https://github.com/AliveTeam/alive_reversing/files/5477437/default.zip)

func:
ChimeLock::VUpdate_40AEF0

**Comment by paulsapps** [comment]
there are some build warnings that might be related to this one
