### ISSUE TITLE
Invisible Zones aren't working

### ISSUE THREAD

**Issue by UltraStars3000** [AliveTeam/alive_reversing#99]
**Found in build:** 1314
**Last working build number:** Unknown (probably never, but never found out until today]

**Description of issue:**
Invisible Zones aren't working!

**Steps to repro:**
Go in an invisible zone and wait for a slig to spot you.

**Function:** IsInInvisibleZone_425710

**Comment by mouzedrift** [comment]
fixed so the issue can be closed :oddtism:
